name: Generate Docker Tags
description: Automatically generates Docker tags from the action environment.
author: Steven Xie <dev@stevenxie.me>
inputs:
  repo:
    required: true
    description: The repository to generate tags for.
runs:
  using: node12
  main: dist/index.js
