name: test
on:
  - pull_request
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate tags
        id: generate-tags
        uses: ./
        with:
          repo: phony
      - name: Print tags
        run: echo "${{ steps.generate-tags.outputs.tags }}"
